local random = require 'src.random'
local r = require 'src.report'
local command = require 'src.fsm.command'
local property = require 'src.property'
local lqc = require 'src.quickcheck'
local lqc_gen = require 'src.lqc_gen'
local elements = lqc_gen.elements


local function is_command(x, cmd_name, func)
  return type(x) == 'table' 
    and x.state_name == cmd_name 
    and x.func == func
    and type(x.args) == 'table'  -- a generator, args will be given to the func
end


local function is_stop_command(x)
  return type(x) == 'table'
    and x.state_name == 'stop'
    and type(x.func) == 'function'
    and type(x.args) == 'table'
end


local function do_setup()
  random.seed()
  lqc.properties = {}
  r.report = function() end
end


describe('command generator', function()
  before_each(do_setup)

  describe('pick function', function()
    it('should pick a command (state name + function + args)', function()
      local cmd_name = 'test_command'
      local function test_func() end
      local spy_check = spy.new(function(x) 
        return is_command(x, cmd_name, test_func) 
      end)
      property 'command generator should pick a valid command for the FSM' {
        generators = { 
          command { cmd_name, test_func, {} } 
        },
        check = spy_check
      }
      lqc.check()
      assert.spy(spy_check).was.called(lqc.iteration_amount)
    end)
  end)

  describe('shrink function', function()
    it('should only shrink the args generated by the command', function()
      local shrunk_value
      r.report_failed = function(_, _, shrunk_vals)
        shrunk_value = shrunk_vals[1]
      end
      local cmd_name = 'another_test_command'
      local test_func = function(x) return x == 0 end

      property 'command generator should only shrink args' {
        generators = {
          command { cmd_name, test_func, {
            elements { 1, 2, 3 }
          }}
        },
        check = function(x)
          return x.func(x.args[1])  -- always fails
        end
      }
      
      for _ = 1, 10 do
        shrunk_value = nil
        lqc.check()
        assert.equal(cmd_name, shrunk_value.state_name) -- TODO replace cmd_name with state_name)
        assert.equal(test_func, shrunk_value.func)
        assert.equal(1, #shrunk_value.args)
        assert.equal(1, shrunk_value.args[1])
      end
    end)
  end)

  describe('stop command', function()
    it('should pick a command with state_name "stop"', function()
      local spy_check = spy.new(function(x) return is_stop_command(x) end)
      property 'stop command has state_name "stop"' {
        generators = { command.stop },
        check = spy_check
      }
      lqc.check()
      assert.spy(spy_check).was.called(lqc.iteration_amount)
    end)
  end)
end)

